### ISSUE TITLE
Need help doing the build

### ISSUE THREAD

**Issue by tmvalente** [mstrlaw/pixel_cube#6]
Hello

I need help in doing the build for linux.
I can't go anywhere with https://github.com/mstrlaw/pixel_cube/blob/master/README.md 

Thank you
TValente

**Comment by mstrlaw** [comment]
Hey @tmvalente !

Right now I don't have access to a linux machine so I haven't tried to build the app on it. Are you getting any errors when trying to build? 

There are some pre-requisites in order to build in either architecture. [Here](https://electronjs.org/docs/development/build-instructions-linux#prerequisites) are the official docs on building for Linux, depending on your distribution. Make sure all that is installed before trying to build the Electron app.

Once you have those, you should run `npm run build:linux`, as specified in the [electron-vue documentation](https://simulatedgreg.gitbooks.io/electron-vue/content/en/using-electron-packager.html).

Also, install any other dependencies that it may warn as being missing from your system.

Let me know if the above helps you.

**Comment by tmvalente** [comment]
Hi mstrlaw

I installed the dependencies, I think none is missing but I can't tell for sure. The OS is Suse12. 
 I am getting this error:


const { say } = require('cfonts')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3

npm ERR! Linux 4.12.14-95.6-default
npm ERR! argv "/usr/bin/node4" "/usr/bin/npm" "run" "build"
npm ERR! node v4.9.1
npm ERR! npm  v3.7.0
npm ERR! code ELIFECYCLE
npm ERR! pixelcube@0.0.2 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pixelcube@0.0.2 build script 'node .electron-vue/build.js && electron-builder'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pixelcube package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node .electron-vue/build.js && electron-builder
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pixelcube
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pixelcube
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:

Any clues?

Thank you
Tânia

**Comment by mstrlaw** [comment]
Hey,

So I got my hand on an clean Ubuntu 14.04 and managed to build the app with these steps below.

Assuming you already have Node & npm installed, you'll still need to have `libbluetooth-dev` to compile properly.

1 - run `sudo apt-get install libbluetooth-dev`

2 - enter the electron directory (pixel_cube/electron/) and run `npm install` to install all necessary dependencies (I think that's what you were missing maybe)

3 - now run `npm run build` to build the app (you can delete the existing _build_ directory before doing so)

If all goes accordingly, you should have a _build/linux-unpacked_ directory. In it is the _pixelcube_ executable. Click or run it with ./pixelcube and it should open the electron app.

Let me know if this helps. Hopefully it'll be +/- the same approach for Suse.

**Comment by tmvalente** [comment]
Good afternoon

Funny that I started to try also on my Ubuntu before I saw your reply.
But I am getting an error anyway :(

npm ERR! node-bluetooth@1.2.5 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-bluetooth@1.2.5 install script 'node-gyp configure build'.

I did installed libbluetooth-dev (came with the dependency libbluetooth3)...
Mine is Ubuntu 18.04.
Keep trying on...
